[package]
name = "keyle"
version = "0.0.1"
authors = ["magicwenli <yxnian@outlook.com>"]
license = "MIT"
description = "This package provides a simple way to style keyboard shortcuts in your documentation."

entrypoint = "src/lib.typ"
keywords = ["kbd", "keyboard"]